# Generated by Django 3.2 on 2021-06-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_update_finder_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='finder.provider'),
        ),
    ]
