
version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=domainfinder
      - POSTGRES_USER=domainadmin
      - POSTGRES_PASSWORD=1234

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=domainfinder
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - DATABASE_USER=domainadmin
      - DATABASE_PASSWORD=1234
