
version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=domainfinder
      - POSTGRES_USER=domainadmin
      - POSTGRES_PASSWORD=1234

  web:
    build: .
    command: /start_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - docker/env/.web
