version: '3.3'

services:
  db:
    image: postgres
    container_name: container-postgresql
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - app_network
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db_data/ebay_api_db_data:/var/lib/postgresql/data/pgdata
  api:
    restart: always
    links:
      - db
    build: .
    container_name: container-ebay-api
    volumes:
      - .:/ebay_api
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true
    networks:
      - app_network
networks:
  app_network:
    driver: bridge