
version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    #volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=domainfinder
      - POSTGRES_USER=domainadmin
      - POSTGRES_PASSWORD=1234

  web:
    build: .
    environment:
      - DOCKER=True
      - CELERY_BROKER=redis://redis:6360/0
      - CELERY_BACKEND=redis://redis:6360/0
    env_file:
      - docker/env/.env
    command: sh /docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    restart: always
    build: .
    command: celery -A applications.finder worker -l info
    environment:
      - POSTGRES_DB=domainfinder
      - POSTGRES_USER=domainadmin
      - POSTGRES_PASSWORD=1234
    depends_on:
      - redis
      - web
      - db

  redis:
    image: "redis:alpine"





